import type { CodeGraph, Symbol, Relationship } from '@pcm/core';

const MERMAID_THEME = `  %% PCM auto-generated dependency graph
  %% Colors: file=#e1f5fe  class=#f3e5f5  func=#e8f5e9  iface=#fff3e0`;

export function sanitizeMermaidId(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, '_').replace(/^(\d)/, '_$1');
}

export function generateArchitectureMD(projectName: string, graph: CodeGraph): string {
  const files = graph.symbols.filter(s => s.type === 'file');
  const classes = graph.symbols.filter(s => s.type === 'class');
  const interfaces = graph.symbols.filter(s => s.type === 'interface');
  const functions = graph.symbols.filter(s => s.type === 'function' || s.type === 'method');

  // Group files by top-level directory
  const dirMap = new Map<string, string[]>();
  for (const f of files) {
    const parts = f.filePath.split('/');
    const dir = parts.length > 1 ? parts[0] : '.';
    if (!dirMap.has(dir)) dirMap.set(dir, []);
    dirMap.get(dir)!.push(f.filePath);
  }

  // Build Mermaid graph
  const mermaidEdges: string[] = [];
  const fileImports = graph.relationships.filter(r => r.type === 'imports');
  for (const rel of fileImports) {
    const sourceFile = graph.symbols.find(s => s.id === rel.sourceId);
    const targetName = (rel.metadata.importSource as string) || '';
    if (sourceFile) {
      const src = sanitizeMermaidId(sourceFile.filePath);
      const tgt = sanitizeMermaidId(targetName);
      if (src !== tgt) {
        mermaidEdges.push(`  ${src} --> ${tgt}`);
      }
    }
  }

  const lines: string[] = [
    `# ${projectName} Architecture\n`,
    `> Auto-generated by PCM on ${graph.scannedAt.toISOString()}`,
    graph.commitHash ? `> Commit: ${graph.commitHash}\n` : '\n',
    '## Overview\n',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Files | ${graph.stats.fileCount} |`,
    `| Classes | ${classes.length} |`,
    `| Interfaces | ${interfaces.length} |`,
    `| Functions/Methods | ${functions.length} |`,
    `| Total Symbols | ${graph.stats.symbolCount} |`,
    `| Total Lines | ${graph.stats.totalLines} |`,
    `| Dependencies | ${graph.stats.relationshipCount} |`,
    '',
  ];

  // Directory structure
  lines.push('## Directory Structure\n');
  lines.push('```');
  lines.push(`${projectName}/`);
  const sortedDirs = Array.from(dirMap.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  for (const [dir, dirFiles] of sortedDirs) {
    lines.push(`├── ${dir}/`);
    for (const f of dirFiles.slice(0, 5)) {
      const baseName = f.split('/').pop() || f;
      lines.push(`│   ├── ${baseName}`);
    }
    if (dirFiles.length > 5) {
      lines.push(`│   └── ... ${dirFiles.length - 5} more files`);
    }
  }
  lines.push('```\n');

  // Mermaid dependency graph
  if (mermaidEdges.length > 0) {
    lines.push('## Dependency Graph\n');
    lines.push('```mermaid');
    lines.push('graph LR');
    lines.push(MERMAID_THEME);
      const uniqueEdges = [...new Set(mermaidEdges)];
    for (const edge of uniqueEdges.slice(0, 50)) {
      lines.push(edge);
    }
    if (uniqueEdges.length > 50) {
      lines.push(`  %% ... ${uniqueEdges.length - 50} more edges`);
    }
    lines.push('```\n');
  }

  // Module details
  lines.push('## Modules\n');
  for (const [dir, dirFiles] of sortedDirs) {
    lines.push(`### ${dir}/ (${dirFiles.length} files)\n`);
    for (const filePath of dirFiles.slice(0, 10)) {
      const fileSymbol = files.find(f => f.filePath === filePath);
      if (!fileSymbol) continue;
      const fileRels = graph.relationships.filter(
        r => r.type === 'imports' && r.sourceId === fileSymbol.id,
      );
      const fileSyms = graph.symbols.filter(
        s => s.type !== 'file' && s.filePath === filePath,
      );
      lines.push(`- **\`${filePath}\`**${fileSymbol.complexity > 5 ? ' ⚠️' : ''}`);
      if (fileRels.length > 0) {
        const targets = fileRels
          .map(r => r.metadata.importSource as string)
          .filter(Boolean)
          .slice(0, 5);
        lines.push(`  - imports: \`${targets.join('`, `')}\``);
        if (fileRels.length > 5) {
          lines.push(`  - ... ${fileRels.length - 5} more imports`);
        }
      }
      if (fileSyms.length > 0) {
        lines.push(`  - symbols: ${fileSyms.map(s => `\`${s.name}\``).join(', ')}`);
      }
    }
    if (dirFiles.length > 10) {
      lines.push(`- ... ${dirFiles.length - 10} more files`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function generateModulesMD(projectName: string, graph: CodeGraph): string {
  const symbols = graph.symbols.filter(s => s.type !== 'file');

  const lines: string[] = [
    `# ${projectName} Module Dictionary\n`,
    `> Auto-generated by PCM on ${graph.scannedAt.toISOString()}\n`,
    `Total: ${symbols.length} symbols\n`,
  ];

  // Group by file
  const byFile = new Map<string, Symbol[]>();
  for (const sym of symbols) {
    if (!byFile.has(sym.filePath)) byFile.set(sym.filePath, []);
    byFile.get(sym.filePath)!.push(sym);
  }

  for (const [filePath, syms] of Array.from(byFile.entries()).sort()) {
    lines.push(`### \`${filePath}\` (${syms.length} symbols)\n`);

    for (const sym of syms) {
      const typeIcon =
        sym.type === 'class' ? '🏛️' :
        sym.type === 'interface' ? '📋' :
        sym.type === 'function' ? '🔧' :
        sym.type === 'method' ? '⚙️' :
        sym.type === 'type' ? '📐' :
        sym.type === 'enum' ? '📊' : '📝';

      lines.push(`#### ${typeIcon} \`${sym.name}\` ${sym.type}`);
      if (sym.docString) lines.push(`> ${sym.docString}`);
      lines.push(`- **Location**: \`${sym.filePath}:${sym.location.startLine}:${sym.location.startColumn}\``);
      lines.push(`- **Lines**: ${sym.lineCount}`);
      if (sym.complexity > 0) {
        lines.push(`- **Complexity**: ${sym.complexity}${sym.complexity > 10 ? ' ⚠️' : ''}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

export function generateHotspotsMD(projectName: string, graph: CodeGraph): string {
  const lines: string[] = [
    `# ${projectName} Complexity Hotspots\n`,
    `> Auto-generated by PCM on ${graph.scannedAt.toISOString()}\n`,
    'Top files and functions ranked by complexity.\n',
    '| Rank | File/Symbol | Type | Complexity | Lines |',
    '|------|-------------|------|-----------|-------|',
  ];

  const hotspots = graph.stats.hotspots;
  for (let i = 0; i < hotspots.length; i++) {
    const h = hotspots[i];
    const symbol = graph.symbols.find(s => s.id === h.symbolId) ||
                   graph.symbols.find(s => s.name === h.name && s.filePath === h.filePath);
    const symType = symbol?.type ?? 'unknown';
    const lineCount = symbol?.lineCount ?? 0;
    const riskIcon = h.riskScore > 15 ? '🔴' : h.riskScore > 8 ? '🟡' : '🟢';
    lines.push(
      `| ${i + 1} | ${riskIcon} \`${h.name}\` | ${symType} | ${h.complexity} | ${lineCount} |`,
    );
  }

  lines.push('');
  lines.push('### 🔍 How to use this');
  lines.push('- 🔴 **High risk**: These files need refactoring attention');
  lines.push('- 🟡 **Medium**: Monitor during code reviews');
  lines.push('- 🟢 **Low**: Acceptable complexity');
  lines.push('');
  lines.push('> 💡 Focus refactoring on the top 3 hotspots for the best ROI.');

  return lines.join('\n');
}
